{{- if .Values.logrotate.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "logrotate.name" . }}-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: {{ include "logrotate.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "logrotate.name" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- end -}}