apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: {{ template "logrotate.name" . }}
  name: {{ template "logrotate.name" . }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
{{ include "logrotate.labels.stakater" . | indent 8 }}
{{ include "logrotate.labels.chart" . | indent 8 }}
      name: {{ template "logrotate.name" . }}
    spec:
{{- if .Values.logrotate.rbac.create }}
{{- if .Values.logrotate.rbac.serviceAccount.name }}
      serviceAccountName: {{ .Values.logrotate.rbac.serviceAccount.name }}
{{- else }}
      serviceAccountName: {{ template "logrotate.name" . }}
{{- end }}
{{- end }}
      containers:
      - name: {{ template "logrotate.name" . }}
        image: "{{ .Values.logrotate.image.name }}:{{ .Values.logrotate.image.tag }}"
{{- if .Values.logrotate.securityContext }}
        securityContext:
{{ toYaml .Values.logrotate.securityContext | indent 10 }}
{{- else }}
        securityContext:
          privileged: true
{{- end }}
        volumeMounts:
         - name: containers
           mountPath: /var/lib/docker/containers
         - name: {{ template "logrotate.name" . }}-config
           mountPath: /etc/{{ template "logrotate.name" . }}.d/k8s-rotator.conf
           subPath: k8s-rotator.conf
        env:
          - name: CRON_SCHEDULE
            value: "{{ .Values.logrotate.environment.cronSchedule }}"
      volumes:
         - hostPath:
             path: /var/lib/docker/containers
           name: containers
         - configMap:
            name: {{ template "logrotate.name" . }}
           name: {{ template "logrotate.name" . }}-config
